const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let songs=[],tab="songs",current=null,deferred=null;const audio=$("#audio");
const db=new Promise((ok,no)=>{let r=indexedDB.open("FKMusic",1);r.onupgradeneeded=()=>r.result.createObjectStore("songs",{keyPath:"id"});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
async function all(){let d=await db;return new Promise(o=>{let q=d.transaction("songs").objectStore("songs").getAll();q.onsuccess=()=>o(q.result)})}
async function put(x){let d=await db;d.transaction("songs","readwrite").objectStore("songs").put(x)}
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function render(){let a=songs.filter(x=>!x.hidden),c=$("#content");if(tab==="songs"||tab==="favorites"){let l=tab==="favorites"?a.filter(x=>x.favorite):a;c.innerHTML=`<div class="actions"><b style="color:#f33">▶ Play all</b><span>${l.length}</span></div>`+(l.length?l.map(song).join(""):`<div class="empty">The playlist is empty.</div>`)}else{let f=tab==="singers"?"artist":tab==="albums"?"album":"folder",m={};a.forEach(x=>m[x[f]]=(m[x[f]]||0)+1);c.innerHTML=`<div class="actions"><span>${Object.keys(m).length} ${f}</span></div>`+Object.entries(m).map(([n,k])=>`<div class="song"><div class="art">♪</div><div><b>${esc(n)}</b><small>${k} song${k>1?"s":""}</small></div></div>`).join("")}$$(".song[data-id]").forEach(e=>e.onclick=v=>{let x=songs.find(z=>z.id===e.dataset.id);v.target.classList.contains("more")?menu(x):open(x)})}
function song(x){return `<div class="song" data-id="${x.id}"><div class="art">♪</div><div><b>${esc(x.name)}</b><small>${esc(x.artist)}</small></div><button class="more">⋮</button></div>`}
async function open(x){current=x;audio.src=URL.createObjectURL(x.blob);$("#mt").textContent=x.name;$("#ma").textContent=x.artist;audio.play().catch(()=>{});player()}
function player(){let x=current;$("#overlay").innerHTML=`<div class="player"><button id="close" style="background:none;border:0;color:white;font-size:28px">⌄</button><div class="cover">♫</div><div class="pt"><h2>${esc(x.name)}</h2><p>${esc(x.artist)} • ${esc(x.album)}</p></div><input id="seek" class="range" type="range" min="0" max="100" value="0"><div class="controls"><button>🔀</button><button id="prev">⏮</button><button class="main" id="pp">⏸</button><button id="nxt">⏭</button><button>🔁</button></div><div class="tools"><button id="fav">♥ Favorite</button><button id="timer">◷ Timer</button><button id="lyrics">Lyrics</button><button id="pm">⋮ More</button></div></div>`;$("#close").onclick=()=>$("#overlay").innerHTML="";$("#pp").onclick=()=>audio.paused?audio.play():audio.pause();$("#fav").onclick=async()=>{x.favorite=!x.favorite;await put(x);render()};$("#timer").onclick=timer;$("#lyrics").onclick=()=>alert("Lyrics are not available for this music");$("#pm").onclick=()=>menu(x);$("#nxt").onclick=next;$("#prev").onclick=prev;$("#seek").oninput=()=>audio.currentTime=audio.duration*$("#seek").value/100}
function timer(){$("#overlay").insertAdjacentHTML("beforeend",`<div class="sheet" id="ts"><div><h3>Timer</h3>${["None","After current track","After 10 minutes","After 20 minutes","After 30 minutes","After 60 minutes"].map(x=>`<button>${x}</button>`).join("")}<button onclick="$('#ts').remove()">Cancel</button></div></div>`)}
function menu(x){$("#overlay").insertAdjacentHTML("beforeend",`<div class="sheet" id="ms"><div><button>Play next</button><button onclick="fav('${x.id}')">Add to Favorites</button><button onclick="hideSong('${x.id}')">Hide</button><button class="danger" onclick="delSong('${x.id}')">Delete</button><button onclick="$('#ms').remove()">Cancel</button></div></div>`)}
window.fav=async id=>{let x=songs.find(z=>z.id===id);x.favorite=true;await put(x);$("#ms").remove();render()};window.hideSong=async id=>{let x=songs.find(z=>z.id===id);x.hidden=true;await put(x);$("#ms").remove();render()};window.delSong=async id=>{if(!confirm("Delete this song permanently?"))return;let d=await db;d.transaction("songs","readwrite").objectStore("songs").delete(id);$("#ms").remove();songs=await all();render()};
function next(){let i=songs.findIndex(x=>x.id===current.id);open(songs[(i+1)%songs.length])}function prev(){let i=songs.findIndex(x=>x.id===current.id);open(songs[(i-1+songs.length)%songs.length])}
$$(".tabs button").forEach(b=>b.onclick=()=>{$$(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");tab=b.dataset.t;render()});
$("#menu").onclick=()=>{$("#overlay").innerHTML=`<div class="sheet"><div><button onclick="scanPage()">Scan local songs</button><button>Playlists</button><button>Help</button></div></div>`};
window.scanPage=()=>{$("#overlay").innerHTML=`<div class="sheet" id="ss"><div class="scan"><div class="big">⌕</div><h2>Scan local songs</h2><p>One tap to select all available music files</p><label><input id="short" type="checkbox"> Do not scan audio files shorter than 60 seconds.</label><br><br><button class="scanbtn" id="scanBtn">Scan</button><p>MP3, MP4 audio, M4A, WAV, OGG</p><input id="files" type="file" accept="audio/*,video/mp4,.mp3,.mp4,.m4a,.wav,.ogg" multiple hidden></div></div>`;$("#scanBtn").onclick=()=>$("#files").click();$("#files").onchange=async e=>{for(let f of e.target.files){let n=f.name.replace(/\.[^.]+$/,""),p=n.split(" - ");await put({id:crypto.randomUUID(),name:p.at(-1)||n,artist:p[0]||"Unknown Artist",album:"Unknown Album",folder:"Music",favorite:false,hidden:false,blob:f})}songs=await all();$("#ss").remove();render()}};
$("#search").onclick=()=>{$("#content").innerHTML=`<div class="search"><input id="q" autofocus placeholder="Search for songs, singers..."></div><div id="res"></div>`;$("#q").oninput=()=>{let q=$("#q").value.toLowerCase();$("#res").innerHTML=songs.filter(x=>(x.name+" "+x.artist).toLowerCase().includes(q)).map(song).join("")}};
const ib=$("#install");ib.hidden=false;ib.onclick=async()=>{if(!deferred){alert("Chrome: ⋮ → Install app / Add to Home screen");return}deferred.prompt();await deferred.userChoice;deferred=null;ib.hidden=false};window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;ib.hidden=false});window.addEventListener("appinstalled",()=>ib.hidden=false);
$("#play").onclick=()=>current&&(audio.paused?audio.play():audio.pause());$("#next").onclick=next;audio.onplay=()=>$("#play").textContent="⏸";audio.onpause=()=>$("#play").textContent="▶";
(async()=>{songs=await all();render()})();